import { CareProfileDraft, PlantCategory, Rarity } from './types';

interface CareProfileEntry {
  match: string[];
  common_name: string;
  scientific_name: string;
  category: PlantCategory;
  rarity: Rarity;
  light: string;
  water: string;
  water_frequency_days: number;
  feed: string;
  feed_frequency_days: number;
  humidity: string;
  temperature: string;
  soil_type: string;
  toxic_to_pets: boolean;
  toxicity_note: string;
  weakness: string;
  resistance: string;
  flavor_text: string;
}

// A curated, hand-written knowledge base of common houseplant care profiles.
// Species ID comes from the vision service; this table fills in the "moves"
// for free with no per-upload API cost. Users can edit every field afterward.
export const CARE_DB: CareProfileEntry[] = [
  {
    match: ['monstera deliciosa', 'monstera', 'swiss cheese plant'],
    common_name: 'Monstera',
    scientific_name: 'Monstera deliciosa',
    category: 'Tropical',
    rarity: 'Uncommon',
    light: 'Bright indirect',
    water: 'Every 7-10 days, top 2in dry',
    water_frequency_days: 8,
    feed: 'Balanced 20-20-20, monthly in spring/summer',
    feed_frequency_days: 30,
    humidity: '50%+',
    temperature: '65-85°F, no drafts below 50°F',
    soil_type: 'Chunky aroid mix (bark, perlite, peat)',
    toxic_to_pets: true,
    toxicity_note: 'Contains insoluble calcium oxalates - toxic to cats and dogs if chewed',
    weakness: 'Cold drafts, overwatering, direct sun scorch',
    resistance: 'Low light (slower growth, no split leaves)',
    flavor_text: 'Famous for its dramatic split leaves once mature enough to fenestrate.',
  },
  {
    match: ['epipremnum aureum', 'pothos', 'devil\'s ivy'],
    common_name: 'Pothos',
    scientific_name: 'Epipremnum aureum',
    category: 'Tropical',
    rarity: 'Common',
    light: 'Low to bright indirect',
    water: 'Every 7-9 days, let soil dry halfway',
    water_frequency_days: 8,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '65-80°F',
    soil_type: 'Standard well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Calcium oxalate crystals - mildly toxic to cats and dogs',
    weakness: 'Overwatering, root rot, soggy soil',
    resistance: 'Neglect, low light, drought',
    flavor_text: 'The famously unkillable vine - trims root instantly in a jar of water.',
  },
  {
    match: ['dracaena trifasciata', 'sansevieria', 'snake plant', 'mother-in-law'],
    common_name: 'Snake Plant',
    scientific_name: 'Dracaena trifasciata',
    category: 'Succulent',
    rarity: 'Common',
    light: 'Low to bright indirect, tolerates full sun',
    water: 'Every 14-21 days, soil fully dry between',
    water_frequency_days: 18,
    feed: 'Cactus/succulent 5-10-5, every 8 weeks in season',
    feed_frequency_days: 56,
    humidity: '30%+ (tolerates dry air)',
    temperature: '60-85°F',
    soil_type: 'Fast-draining cactus/succulent mix',
    toxic_to_pets: true,
    toxicity_note: 'Saponins - can cause GI upset in cats and dogs',
    weakness: 'Overwatering, root rot, cold temps below 50°F',
    resistance: 'Drought, low light, neglect',
    flavor_text: 'Stiff, sword-like leaves that seem to shrug off almost any care mistake.',
  },
  {
    match: ['zamioculcas zamiifolia', 'zz plant'],
    common_name: 'ZZ Plant',
    scientific_name: 'Zamioculcas zamiifolia',
    category: 'Foliage',
    rarity: 'Common',
    light: 'Low to bright indirect',
    water: 'Every 14-18 days, soil fully dry between',
    water_frequency_days: 16,
    feed: 'Balanced 10-10-10, every 8 weeks in season',
    feed_frequency_days: 56,
    humidity: '30%+',
    temperature: '65-80°F',
    soil_type: 'Well-draining potting mix with perlite',
    toxic_to_pets: true,
    toxicity_note: 'Calcium oxalates - toxic to cats and dogs if ingested',
    weakness: 'Overwatering, waterlogged soil',
    resistance: 'Low light, drought, neglect',
    flavor_text: 'Grows from thick rhizomes that store water for weeks of benign neglect.',
  },
  {
    match: ['ficus lyrata', 'fiddle leaf fig', 'fiddle-leaf fig'],
    common_name: 'Fiddle Leaf Fig',
    scientific_name: 'Ficus lyrata',
    category: 'Tropical',
    rarity: 'Rare',
    light: 'Bright indirect, some direct morning sun',
    water: 'Every 7-10 days, top 2in dry, consistent schedule',
    water_frequency_days: 8,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '50%+',
    temperature: '65-80°F, hates drafts and sudden moves',
    soil_type: 'Well-draining potting mix, slightly acidic',
    toxic_to_pets: true,
    toxicity_note: 'Sap and leaves toxic to cats and dogs if chewed',
    weakness: 'Being moved, drafts, inconsistent watering, low light',
    resistance: 'Bright light tolerant once acclimated',
    flavor_text: 'Notoriously dramatic - drops leaves at the slightest change in routine.',
  },
  {
    match: ['ficus elastica', 'rubber plant', 'rubber tree'],
    common_name: 'Rubber Plant',
    scientific_name: 'Ficus elastica',
    category: 'Tropical',
    rarity: 'Uncommon',
    light: 'Bright indirect',
    water: 'Every 8-10 days, top 2in dry',
    water_frequency_days: 9,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '60-80°F',
    soil_type: 'Well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Milky sap irritates skin and is toxic to cats and dogs',
    weakness: 'Overwatering, cold drafts',
    resistance: 'Low light, dry air, some neglect',
    flavor_text: 'Glossy, thick leaves that were once tapped for actual rubber production.',
  },
  {
    match: ['philodendron hederaceum', 'heartleaf philodendron'],
    common_name: 'Heartleaf Philodendron',
    scientific_name: 'Philodendron hederaceum',
    category: 'Tropical',
    rarity: 'Common',
    light: 'Low to bright indirect',
    water: 'Every 7-9 days, top 1-2in dry',
    water_frequency_days: 8,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '65-80°F',
    soil_type: 'Standard well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Calcium oxalates - toxic to cats and dogs',
    weakness: 'Overwatering, cold drafts',
    resistance: 'Low light, drought, neglect',
    flavor_text: 'A trailing classic that will happily climb a moss pole toward the light.',
  },
  {
    match: ['philodendron bipinnatifidum', 'philodendron selloum', 'tree philodendron'],
    common_name: 'Tree Philodendron',
    scientific_name: 'Philodendron bipinnatifidum',
    category: 'Tropical',
    rarity: 'Uncommon',
    light: 'Bright indirect',
    water: 'Every 8-10 days, top 2in dry',
    water_frequency_days: 9,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '50%+',
    temperature: '65-80°F',
    soil_type: 'Chunky, well-draining aroid mix',
    toxic_to_pets: true,
    toxicity_note: 'Calcium oxalates - toxic to cats and dogs',
    weakness: 'Overwatering, cold drafts, low humidity browning',
    resistance: 'Low light, drought',
    flavor_text: 'Deeply lobed leaves that get more dramatic with every new growth spurt.',
  },
  {
    match: ['spathiphyllum', 'peace lily'],
    common_name: 'Peace Lily',
    scientific_name: 'Spathiphyllum wallisii',
    category: 'Flowering',
    rarity: 'Common',
    light: 'Low to medium indirect',
    water: 'Every 5-7 days, keep lightly moist, droops when thirsty',
    water_frequency_days: 6,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '50%+',
    temperature: '65-80°F',
    soil_type: 'Rich, moisture-retentive potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Calcium oxalates - toxic to cats and dogs',
    weakness: 'Underwatering (dramatic drooping), direct sun scorch',
    resistance: 'Low light',
    flavor_text: 'Dramatically wilts when thirsty, then perks back up minutes after watering.',
  },
  {
    match: ['chlorophytum comosum', 'spider plant'],
    common_name: 'Spider Plant',
    scientific_name: 'Chlorophytum comosum',
    category: 'Foliage',
    rarity: 'Common',
    light: 'Bright indirect to medium',
    water: 'Every 6-8 days, top 1in dry',
    water_frequency_days: 7,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '60-80°F',
    soil_type: 'Standard well-draining potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic, though can cause mild GI upset in large amounts',
    weakness: 'Fluoride/chlorine in tap water causes brown tips',
    resistance: 'Neglect, low light, drought',
    flavor_text: 'Sends out baby "pups" on long stems - each one can be propagated into a new plant.',
  },
  {
    match: ['aloe vera', 'aloe barbadensis'],
    common_name: 'Aloe Vera',
    scientific_name: 'Aloe vera',
    category: 'Succulent',
    rarity: 'Common',
    light: 'Bright direct to indirect',
    water: 'Every 14-21 days, soil fully dry between',
    water_frequency_days: 17,
    feed: 'Cactus/succulent 5-10-5, every 8 weeks in season',
    feed_frequency_days: 56,
    humidity: '30%+',
    temperature: '55-85°F',
    soil_type: 'Fast-draining cactus/succulent mix',
    toxic_to_pets: true,
    toxicity_note: 'Saponins - toxic to cats and dogs if ingested (gel itself is used topically on humans)',
    weakness: 'Overwatering, root rot, frost',
    resistance: 'Drought, heat, neglect',
    flavor_text: 'Its gel-filled leaves have been used as a home remedy for burns for centuries.',
  },
  {
    match: ['echeveria'],
    common_name: 'Echeveria',
    scientific_name: 'Echeveria elegans',
    category: 'Succulent',
    rarity: 'Uncommon',
    light: 'Bright direct',
    water: 'Every 12-16 days, soil fully dry between',
    water_frequency_days: 14,
    feed: 'Cactus/succulent 5-10-5, every 8 weeks in season',
    feed_frequency_days: 56,
    humidity: '20-40%',
    temperature: '65-80°F',
    soil_type: 'Fast-draining cactus/succulent mix',
    toxic_to_pets: false,
    toxicity_note: 'Generally considered non-toxic to cats and dogs',
    weakness: 'Overwatering, low light (etiolation/stretching)',
    resistance: 'Drought, heat',
    flavor_text: 'Forms a near-perfect rosette that looks like a stone flower.',
  },
  {
    match: ['haworthia'],
    common_name: 'Haworthia',
    scientific_name: 'Haworthia fasciata',
    category: 'Succulent',
    rarity: 'Uncommon',
    light: 'Bright indirect (avoid harsh direct sun)',
    water: 'Every 14-18 days, soil fully dry between',
    water_frequency_days: 16,
    feed: 'Cactus/succulent 5-10-5, every 8 weeks in season',
    feed_frequency_days: 56,
    humidity: '20-40%',
    temperature: '65-80°F',
    soil_type: 'Fast-draining cactus/succulent mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Direct hot sun (scorching), overwatering',
    resistance: 'Low light, drought',
    flavor_text: 'Zebra-striped warty leaves that stay compact for years.',
  },
  {
    match: ['crassula ovata', 'jade plant'],
    common_name: 'Jade Plant',
    scientific_name: 'Crassula ovata',
    category: 'Succulent',
    rarity: 'Common',
    light: 'Bright direct to indirect',
    water: 'Every 14-21 days, soil fully dry between',
    water_frequency_days: 17,
    feed: 'Cactus/succulent 5-10-5, every 8 weeks in season',
    feed_frequency_days: 56,
    humidity: '20-40%',
    temperature: '65-80°F',
    soil_type: 'Fast-draining cactus/succulent mix',
    toxic_to_pets: true,
    toxicity_note: 'Mildly toxic to cats and dogs, can cause vomiting/lethargy',
    weakness: 'Overwatering, root rot, frost',
    resistance: 'Drought, neglect',
    flavor_text: 'A "money tree" said to bring good fortune, growing sturdier every year.',
  },
  {
    match: ['opuntia', 'prickly pear'],
    common_name: 'Prickly Pear Cactus',
    scientific_name: 'Opuntia microdasys',
    category: 'Succulent',
    rarity: 'Uncommon',
    light: 'Bright direct',
    water: 'Every 18-24 days, soil fully dry between',
    water_frequency_days: 21,
    feed: 'Cactus/succulent 5-10-5, every 8 weeks in season',
    feed_frequency_days: 56,
    humidity: '20-30%',
    temperature: '65-90°F',
    soil_type: 'Very fast-draining cactus mix with extra grit',
    toxic_to_pets: false,
    toxicity_note: 'Not toxic, but glochids (tiny spines) are a physical hazard to pets',
    weakness: 'Overwatering, low light, cold/frost',
    resistance: 'Drought, intense heat, neglect',
    flavor_text: 'Covered in tiny glochid spines that are nearly invisible but very memorable.',
  },
  {
    match: ['schlumbergera', 'christmas cactus', 'holiday cactus'],
    common_name: 'Christmas Cactus',
    scientific_name: 'Schlumbergera bridgesii',
    category: 'Succulent',
    rarity: 'Uncommon',
    light: 'Bright indirect',
    water: 'Every 10-14 days, top 1in dry',
    water_frequency_days: 12,
    feed: 'Bloom-boosting 10-30-20, monthly during bud season',
    feed_frequency_days: 30,
    humidity: '40-50%',
    temperature: '60-75°F',
    soil_type: 'Well-draining, humus-rich mix',
    toxic_to_pets: false,
    toxicity_note: 'Considered non-toxic to cats and dogs',
    weakness: 'Overwatering, dry air bud drop',
    resistance: 'Low light, cooler temps',
    flavor_text: 'Blooms with showy pink-red flowers right around the winter holidays.',
  },
  {
    match: ['nephrolepis exaltata', 'boston fern'],
    common_name: 'Boston Fern',
    scientific_name: 'Nephrolepis exaltata',
    category: 'Fern',
    rarity: 'Uncommon',
    light: 'Bright indirect, no direct sun',
    water: 'Every 4-6 days, keep evenly moist',
    water_frequency_days: 5,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '60%+',
    temperature: '65-75°F',
    soil_type: 'Rich, moisture-retentive potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Dry air (crispy fronds), direct sun, letting soil dry out',
    resistance: 'Low light',
    flavor_text: 'Lush, arching fronds that crave a humid bathroom windowsill.',
  },
  {
    match: ['adiantum', 'maidenhair fern'],
    common_name: 'Maidenhair Fern',
    scientific_name: 'Adiantum raddianum',
    category: 'Fern',
    rarity: 'Rare',
    light: 'Bright indirect, no direct sun',
    water: 'Every 3-4 days, never let soil dry out',
    water_frequency_days: 3,
    feed: 'Balanced 10-10-10 (heavily diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '70%+',
    temperature: '65-75°F',
    soil_type: 'Rich, moisture-retentive potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Any dryness at all (fronds collapse fast), drafts',
    resistance: 'Very little - notoriously fussy',
    flavor_text: 'Delicate black stems and feathery fronds that wilt dramatically if neglected even briefly.',
  },
  {
    match: ['asplenium nidus', "bird's nest fern", 'birds nest fern'],
    common_name: "Bird's Nest Fern",
    scientific_name: 'Asplenium nidus',
    category: 'Fern',
    rarity: 'Uncommon',
    light: 'Medium to bright indirect',
    water: 'Every 6-8 days, top 1in dry',
    water_frequency_days: 7,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '60%+',
    temperature: '65-80°F',
    soil_type: 'Rich, well-draining potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Direct sun, letting soil fully dry, touching new fronds',
    resistance: 'Low light',
    flavor_text: 'Wavy, glossy fronds unfurl from a central rosette like a leafy nest.',
  },
  {
    match: ['platycerium', 'staghorn fern'],
    common_name: 'Staghorn Fern',
    scientific_name: 'Platycerium bifurcatum',
    category: 'Fern',
    rarity: 'Rare',
    light: 'Bright indirect',
    water: 'Every 7-10 days, soak-and-dry or mist heavily',
    water_frequency_days: 8,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '60%+',
    temperature: '65-80°F',
    soil_type: 'Mounted on bark/moss rather than potted in soil',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Low humidity, overwatering the basal shield frond',
    resistance: 'Low light once established',
    flavor_text: 'Grows antler-shaped fronds and is often mounted on wood like living wall art.',
  },
  {
    match: ['phalaenopsis', 'moth orchid'],
    common_name: 'Moth Orchid',
    scientific_name: 'Phalaenopsis amabilis',
    category: 'Flowering',
    rarity: 'Rare',
    light: 'Bright indirect, no direct sun',
    water: 'Every 7 days, soak-and-drain, never sit in water',
    water_frequency_days: 7,
    feed: 'Orchid-specific 20-20-20 (diluted), every 2 weeks in growing season',
    feed_frequency_days: 14,
    humidity: '50-70%',
    temperature: '65-80°F, needs a 10°F night drop to rebloom',
    soil_type: 'Orchid bark/sphagnum mix, never regular potting soil',
    toxic_to_pets: false,
    toxicity_note: 'Generally non-toxic to cats and dogs',
    weakness: 'Overwatering roots, direct sun, tap water salt buildup',
    resistance: 'Low light (just won\'t rebloom easily)',
    flavor_text: 'Its aerial roots hunt for moisture in the air, not the potting mix.',
  },
  {
    match: ['anthurium andraeanum', 'anthurium', 'flamingo flower'],
    common_name: 'Anthurium',
    scientific_name: 'Anthurium andraeanum',
    category: 'Flowering',
    rarity: 'Rare',
    light: 'Bright indirect',
    water: 'Every 6-8 days, top 1-2in dry',
    water_frequency_days: 7,
    feed: 'Bloom-boosting 10-30-20 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '60%+',
    temperature: '65-80°F',
    soil_type: 'Chunky, well-draining aroid mix',
    toxic_to_pets: true,
    toxicity_note: 'Calcium oxalates - toxic to cats and dogs',
    weakness: 'Low humidity, overwatering, cold drafts',
    resistance: 'Low light (fewer blooms)',
    flavor_text: 'Glossy heart-shaped spathes in red or pink that can rebloom for months at a time.',
  },
  {
    match: ['saintpaulia', 'african violet'],
    common_name: 'African Violet',
    scientific_name: 'Saintpaulia ionantha',
    category: 'Flowering',
    rarity: 'Uncommon',
    light: 'Bright indirect, no direct sun',
    water: 'Every 5-7 days, bottom-water to avoid leaf spotting',
    water_frequency_days: 6,
    feed: 'African violet-specific 14-12-14, every 4 weeks',
    feed_frequency_days: 28,
    humidity: '50%+',
    temperature: '65-75°F',
    soil_type: 'Light, well-draining African violet mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Cold water on leaves (spotting), direct sun, overwatering crown',
    resistance: 'Low light',
    flavor_text: 'Fuzzy leaves and clusters of purple blooms that flower nearly year-round.',
  },
  {
    match: ['hibiscus rosa-sinensis', 'hibiscus'],
    common_name: 'Tropical Hibiscus',
    scientific_name: 'Hibiscus rosa-sinensis',
    category: 'Flowering',
    rarity: 'Uncommon',
    light: 'Bright direct, 4+ hours daily',
    water: 'Every 3-5 days, keep evenly moist in growing season',
    water_frequency_days: 4,
    feed: 'Bloom-boosting 10-30-20, every 2 weeks in growing season',
    feed_frequency_days: 14,
    humidity: '40%+',
    temperature: '65-85°F',
    soil_type: 'Rich, well-draining potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Generally considered non-toxic to cats and dogs',
    weakness: 'Underwatering (bud drop), low light',
    resistance: 'Heat, heavy feeding',
    flavor_text: 'Each flashy bloom lasts only a day or two, but new ones keep coming all season.',
  },
  {
    match: ['calathea', 'goeppertia'],
    common_name: 'Calathea',
    scientific_name: 'Goeppertia insignis',
    category: 'Foliage',
    rarity: 'Rare',
    light: 'Medium indirect, no direct sun',
    water: 'Every 5-7 days, keep evenly moist, use filtered water',
    water_frequency_days: 6,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '60%+',
    temperature: '65-80°F',
    soil_type: 'Rich, moisture-retentive, well-draining mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Tap water fluoride/chlorine (leaf spotting), low humidity, direct sun',
    resistance: 'Low light',
    flavor_text: 'Its patterned leaves rise and fold at night like praying hands.',
  },
  {
    match: ['maranta leuconeura', 'prayer plant'],
    common_name: 'Prayer Plant',
    scientific_name: 'Maranta leuconeura',
    category: 'Foliage',
    rarity: 'Rare',
    light: 'Medium indirect, no direct sun',
    water: 'Every 5-7 days, keep evenly moist',
    water_frequency_days: 6,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '55%+',
    temperature: '65-80°F',
    soil_type: 'Rich, moisture-retentive, well-draining mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Low humidity, direct sun, tap water salts',
    resistance: 'Low light',
    flavor_text: 'Leaves fold upward each night, giving this plant its "prayer" nickname.',
  },
  {
    match: ['begonia rex'],
    common_name: 'Rex Begonia',
    scientific_name: 'Begonia rex',
    category: 'Foliage',
    rarity: 'Rare',
    light: 'Medium indirect',
    water: 'Every 6-8 days, top 1in dry',
    water_frequency_days: 7,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '50%+',
    temperature: '65-80°F',
    soil_type: 'Well-draining, humus-rich potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Soluble calcium oxalates, most concentrated in rhizomes - toxic to cats and dogs',
    weakness: 'Overwatering (powdery mildew), direct sun',
    resistance: 'Low light',
    flavor_text: 'Swirled metallic leaf patterns that look almost painted on.',
  },
  {
    match: ['pilea peperomioides', 'chinese money plant'],
    common_name: 'Chinese Money Plant',
    scientific_name: 'Pilea peperomioides',
    category: 'Foliage',
    rarity: 'Uncommon',
    light: 'Bright indirect',
    water: 'Every 7-9 days, top 1-2in dry',
    water_frequency_days: 8,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '60-80°F',
    soil_type: 'Well-draining potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Overwatering, low light (leggy growth)',
    resistance: 'Neglect, drought',
    flavor_text: 'Its coin-shaped leaves make it a favorite for cheerful windowsill propagations.',
  },
  {
    match: ['peperomia obtusifolia', 'peperomia'],
    common_name: 'Baby Rubber Plant',
    scientific_name: 'Peperomia obtusifolia',
    category: 'Foliage',
    rarity: 'Common',
    light: 'Medium to bright indirect',
    water: 'Every 9-12 days, soil mostly dry between',
    water_frequency_days: 10,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '65-80°F',
    soil_type: 'Well-draining potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Overwatering, root rot',
    resistance: 'Low light, drought, neglect',
    flavor_text: 'Thick, water-storing leaves make it forgiving of an inconsistent schedule.',
  },
  {
    match: ['hedera helix', 'english ivy'],
    common_name: 'English Ivy',
    scientific_name: 'Hedera helix',
    category: 'Foliage',
    rarity: 'Common',
    light: 'Medium to bright indirect',
    water: 'Every 6-8 days, top 1in dry',
    water_frequency_days: 7,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '50-75°F',
    soil_type: 'Standard well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Triterpenoid saponins - toxic to cats and dogs',
    weakness: 'Hot dry air (spider mites), overwatering',
    resistance: 'Cool temps, low light',
    flavor_text: 'A vigorous trailing vine that has climbed buildings for centuries.',
  },
  {
    match: ['tradescantia zebrina', 'wandering jew', 'inch plant'],
    common_name: 'Wandering Dude',
    scientific_name: 'Tradescantia zebrina',
    category: 'Foliage',
    rarity: 'Common',
    light: 'Bright indirect to some direct',
    water: 'Every 5-7 days, top 1in dry',
    water_frequency_days: 6,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '60-80°F',
    soil_type: 'Standard well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Sap can irritate skin; mildly toxic to cats and dogs',
    weakness: 'Low light (color fades, gets leggy)',
    resistance: 'Neglect, fast to propagate from cuttings',
    flavor_text: 'Iridescent purple-and-silver striped leaves that trail beautifully from a shelf.',
  },
  {
    match: ['ocimum basilicum', 'basil'],
    common_name: 'Basil',
    scientific_name: 'Ocimum basilicum',
    category: 'Herb',
    rarity: 'Common',
    light: 'Bright direct, 6+ hours daily',
    water: 'Every 2-3 days, keep evenly moist',
    water_frequency_days: 2,
    feed: 'Balanced 10-10-10 (diluted), every 3 weeks in growing season',
    feed_frequency_days: 21,
    humidity: '40%+',
    temperature: '65-85°F',
    soil_type: 'Rich, well-draining potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Underwatering, cold drafts below 50°F',
    resistance: 'Heat, frequent harvesting encourages growth',
    flavor_text: 'Pinch the tops often - it rewards frequent harvesting with bushier growth.',
  },
  {
    match: ['mentha', 'mint'],
    common_name: 'Mint',
    scientific_name: 'Mentha spicata',
    category: 'Herb',
    rarity: 'Common',
    light: 'Bright indirect to some direct',
    water: 'Every 3-4 days, keep evenly moist',
    water_frequency_days: 3,
    feed: 'Balanced 10-10-10 (diluted), every 3 weeks in growing season',
    feed_frequency_days: 21,
    humidity: '40%+',
    temperature: '60-80°F',
    soil_type: 'Rich, moisture-retentive potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Drying out completely, cramped roots (best kept contained)',
    resistance: 'Neglect, cooler temps, spreads aggressively',
    flavor_text: 'So vigorous it will take over a garden bed - keep it potted to stay in control.',
  },
  {
    match: ['rosmarinus officinalis', 'salvia rosmarinus', 'rosemary'],
    common_name: 'Rosemary',
    scientific_name: 'Salvia rosmarinus',
    category: 'Herb',
    rarity: 'Uncommon',
    light: 'Bright direct, 6+ hours daily',
    water: 'Every 8-10 days, soil mostly dry between',
    water_frequency_days: 9,
    feed: 'Balanced 10-10-10 (diluted), every 6 weeks in growing season',
    feed_frequency_days: 42,
    humidity: '30-40%',
    temperature: '60-80°F',
    soil_type: 'Fast-draining, sandy potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Overwatering (root rot), poor air circulation (powdery mildew)',
    resistance: 'Drought, heat, poor soil',
    flavor_text: 'A woody Mediterranean herb that prefers to be a little thirsty.',
  },
  {
    match: ['lavandula', 'lavender'],
    common_name: 'Lavender',
    scientific_name: 'Lavandula angustifolia',
    category: 'Herb',
    rarity: 'Uncommon',
    light: 'Bright direct, 6+ hours daily',
    water: 'Every 9-12 days, soil mostly dry between',
    water_frequency_days: 10,
    feed: 'Balanced 10-10-10 (diluted), every 6 weeks in growing season',
    feed_frequency_days: 42,
    humidity: '30-40%',
    temperature: '60-80°F',
    soil_type: 'Fast-draining, sandy/gritty potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Linalool - mildly toxic to cats and dogs in large amounts',
    weakness: 'Overwatering, humid stagnant air',
    resistance: 'Drought, heat, poor soil',
    flavor_text: 'Fragrant purple spikes that dry beautifully for sachets long after cutting.',
  },
  {
    match: ['dionaea muscipula', 'venus flytrap'],
    common_name: 'Venus Flytrap',
    scientific_name: 'Dionaea muscipula',
    category: 'Carnivorous',
    rarity: 'Rare',
    light: 'Bright direct, 4+ hours daily',
    water: 'Every 3-4 days, tray method with distilled/rain water only',
    water_frequency_days: 3,
    feed: 'No fertilizer - feed live insects occasionally instead',
    feed_frequency_days: 45,
    humidity: '50%+',
    temperature: '65-80°F, needs a cool winter dormancy',
    soil_type: 'Nutrient-free sphagnum moss / peat-perlite mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Tap water minerals, fertilizer, low light, dry soil',
    resistance: 'Poor/nutrient-free soil (thrives on it)',
    flavor_text: 'Snaps its hinged leaves shut on unsuspecting insects in under a second.',
  },
  {
    match: ['sarracenia', 'pitcher plant'],
    common_name: 'Pitcher Plant',
    scientific_name: 'Sarracenia purpurea',
    category: 'Carnivorous',
    rarity: 'Rare',
    light: 'Bright direct, 6+ hours daily',
    water: 'Every 3-4 days, tray method with distilled/rain water only',
    water_frequency_days: 3,
    feed: 'No fertilizer needed - traps its own insects',
    feed_frequency_days: 60,
    humidity: '50%+',
    temperature: '60-85°F, needs a cool winter dormancy',
    soil_type: 'Nutrient-free sphagnum moss / peat-perlite mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Tap water minerals, fertilizer, drying out',
    resistance: 'Poor/nutrient-free soil, full sun',
    flavor_text: 'Its tall, nectar-lined tubes lure insects in, then trap them with slippery walls.',
  },
  {
    match: ['drosera', 'sundew'],
    common_name: 'Sundew',
    scientific_name: 'Drosera capensis',
    category: 'Carnivorous',
    rarity: 'Holo',
    light: 'Bright direct, 6+ hours daily',
    water: 'Every 2-3 days, tray method with distilled/rain water only',
    water_frequency_days: 2,
    feed: 'No fertilizer - catches its own gnats and fruit flies',
    feed_frequency_days: 30,
    humidity: '60%+',
    temperature: '65-85°F',
    soil_type: 'Nutrient-free sphagnum moss / peat-perlite mix',
    toxic_to_pets: false,
    toxicity_note: 'Non-toxic to cats and dogs',
    weakness: 'Tap water minerals, fertilizer, drying out completely',
    resistance: 'Poor/nutrient-free soil',
    flavor_text: 'Sparkling, dew-covered tentacles that are actually a sticky insect trap.',
  },
  {
    match: ['strelitzia nicolai', 'strelitzia reginae', 'bird of paradise'],
    common_name: 'Bird of Paradise',
    scientific_name: 'Strelitzia nicolai',
    category: 'Tropical',
    rarity: 'Rare',
    light: 'Bright direct to indirect',
    water: 'Every 7-9 days, top 2in dry',
    water_frequency_days: 8,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '50%+',
    temperature: '65-80°F',
    soil_type: 'Rich, well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Mildly toxic to cats and dogs, can cause GI upset',
    weakness: 'Low light, cold drafts, underwatering',
    resistance: 'Once mature, fairly tolerant of missed waterings',
    flavor_text: 'Given enough light, it can eventually produce dramatic orange crane-like blooms.',
  },
  {
    match: ['dracaena marginata', 'dragon tree'],
    common_name: 'Dragon Tree',
    scientific_name: 'Dracaena marginata',
    category: 'Foliage',
    rarity: 'Uncommon',
    light: 'Medium to bright indirect',
    water: 'Every 10-14 days, soil mostly dry between',
    water_frequency_days: 12,
    feed: 'Balanced 10-10-10, every 6 weeks in growing season',
    feed_frequency_days: 42,
    humidity: '30%+',
    temperature: '65-80°F',
    soil_type: 'Well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Saponins - toxic to cats and dogs, causes vomiting',
    weakness: 'Fluoride in tap water (leaf tip burn), overwatering',
    resistance: 'Low light, drought, neglect',
    flavor_text: 'Thin, arching red-edged leaves atop a slow-growing, sculptural trunk.',
  },
];

const CATEGORY_FALLBACKS: Record<PlantCategory, Omit<CareProfileEntry, 'match' | 'common_name' | 'scientific_name'>> = {
  Tropical: {
    category: 'Tropical',
    rarity: 'Common',
    light: 'Bright indirect',
    water: 'Every 7 days, top 2in dry',
    water_frequency_days: 7,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '50%+',
    temperature: '65-80°F',
    soil_type: 'Well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Unconfirmed - assume toxic to pets until verified, keep out of reach',
    weakness: 'Overwatering, cold drafts',
    resistance: 'Low light',
    flavor_text: 'A lush addition to the collection, still being profiled.',
  },
  Succulent: {
    category: 'Succulent',
    rarity: 'Common',
    light: 'Bright direct to indirect',
    water: 'Every 14-18 days, soil fully dry between',
    water_frequency_days: 16,
    feed: 'Cactus/succulent 5-10-5, every 8 weeks in season',
    feed_frequency_days: 56,
    humidity: '20-40%',
    temperature: '65-85°F',
    soil_type: 'Fast-draining cactus/succulent mix',
    toxic_to_pets: false,
    toxicity_note: 'Unconfirmed - verify toxicity for this specific species',
    weakness: 'Overwatering, root rot',
    resistance: 'Drought, neglect',
    flavor_text: 'A hardy little water-hoarder still being profiled.',
  },
  Fern: {
    category: 'Fern',
    rarity: 'Uncommon',
    light: 'Medium to bright indirect, no direct sun',
    water: 'Every 5-7 days, keep evenly moist',
    water_frequency_days: 6,
    feed: 'Balanced 10-10-10 (diluted), monthly in growing season',
    feed_frequency_days: 30,
    humidity: '60%+',
    temperature: '65-75°F',
    soil_type: 'Rich, moisture-retentive potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Generally non-toxic, but verify for this species',
    weakness: 'Dry air, letting soil dry out',
    resistance: 'Low light',
    flavor_text: 'A humidity-loving frond still being profiled.',
  },
  Flowering: {
    category: 'Flowering',
    rarity: 'Uncommon',
    light: 'Bright indirect',
    water: 'Every 6-8 days, top 1-2in dry',
    water_frequency_days: 7,
    feed: 'Bloom-boosting 10-30-20, every 2-4 weeks in growing season',
    feed_frequency_days: 21,
    humidity: '50%+',
    temperature: '65-80°F',
    soil_type: 'Rich, well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Unconfirmed - assume toxic to pets until verified, keep out of reach',
    weakness: 'Low light (fewer blooms), overwatering',
    resistance: 'Low light survival (just less flowering)',
    flavor_text: 'A budding beauty still being profiled.',
  },
  Foliage: {
    category: 'Foliage',
    rarity: 'Common',
    light: 'Medium to bright indirect',
    water: 'Every 7-9 days, top 1-2in dry',
    water_frequency_days: 8,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '65-80°F',
    soil_type: 'Well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Unconfirmed - assume toxic to pets until verified, keep out of reach',
    weakness: 'Overwatering, cold drafts',
    resistance: 'Low light, some neglect',
    flavor_text: 'A leafy specimen still being profiled.',
  },
  Herb: {
    category: 'Herb',
    rarity: 'Common',
    light: 'Bright direct, 6+ hours daily',
    water: 'Every 3-4 days, keep evenly moist',
    water_frequency_days: 3,
    feed: 'Balanced 10-10-10 (diluted), every 3 weeks in growing season',
    feed_frequency_days: 21,
    humidity: '40%+',
    temperature: '60-80°F',
    soil_type: 'Rich, well-draining potting mix',
    toxic_to_pets: false,
    toxicity_note: 'Generally non-toxic, but verify for this species',
    weakness: 'Drying out, cold drafts',
    resistance: 'Frequent harvesting encourages growth',
    flavor_text: 'A kitchen-counter herb still being profiled.',
  },
  Carnivorous: {
    category: 'Carnivorous',
    rarity: 'Rare',
    light: 'Bright direct, 4-6 hours daily',
    water: 'Every 3-4 days, tray method with distilled/rain water only',
    water_frequency_days: 3,
    feed: 'No fertilizer - feed occasional live insects instead',
    feed_frequency_days: 45,
    humidity: '50%+',
    temperature: '65-80°F',
    soil_type: 'Nutrient-free sphagnum moss / peat-perlite mix',
    toxic_to_pets: false,
    toxicity_note: 'Generally non-toxic to cats and dogs',
    weakness: 'Tap water minerals, fertilizer',
    resistance: 'Poor/nutrient-free soil',
    flavor_text: 'A carnivorous curiosity still being profiled.',
  },
  Other: {
    category: 'Other',
    rarity: 'Common',
    light: 'Bright indirect',
    water: 'Every 7 days, top 2in dry',
    water_frequency_days: 7,
    feed: 'Balanced 10-10-10, monthly in growing season',
    feed_frequency_days: 30,
    humidity: '40%+',
    temperature: '65-80°F',
    soil_type: 'Well-draining potting mix',
    toxic_to_pets: true,
    toxicity_note: 'Unconfirmed - verify toxicity for this specific species',
    weakness: 'Overwatering',
    resistance: 'Low light',
    flavor_text: 'A new addition still being profiled - edit me once you know more!',
  },
};

const FAMILY_CATEGORY_HINTS: [RegExp, PlantCategory][] = [
  [/cactaceae/i, 'Succulent'],
  [/crassulaceae/i, 'Succulent'],
  [/asphodelaceae/i, 'Succulent'],
  [/polypodiaceae|pteridaceae|aspleniaceae|dryopteridaceae/i, 'Fern'],
  [/orchidaceae/i, 'Flowering'],
  [/lamiaceae/i, 'Herb'],
  [/droseraceae|sarraceniaceae|nepenthaceae/i, 'Carnivorous'],
  [/araceae|marantaceae|arecaceae/i, 'Foliage'],
];

export function guessCategoryFromTaxonomy(taxonomyText: string): PlantCategory | null {
  for (const [re, category] of FAMILY_CATEGORY_HINTS) {
    if (re.test(taxonomyText)) return category;
  }
  return null;
}

export function findCareProfile(
  commonName: string,
  scientificName: string,
  confidence: number,
  categoryHint?: PlantCategory | null
): CareProfileDraft {
  const haystack = `${commonName} ${scientificName}`.toLowerCase();
  const hit = CARE_DB.find((entry) => entry.match.some((m) => haystack.includes(m)));

  if (hit) {
    return {
      common_name: hit.common_name,
      scientific_name: hit.scientific_name,
      category: hit.category,
      rarity: hit.rarity,
      light: hit.light,
      water: hit.water,
      water_frequency_days: hit.water_frequency_days,
      feed: hit.feed,
      feed_frequency_days: hit.feed_frequency_days,
      humidity: hit.humidity,
      temperature: hit.temperature,
      soil_type: hit.soil_type,
      toxic_to_pets: hit.toxic_to_pets,
      toxicity_note: hit.toxicity_note,
      weakness: hit.weakness,
      resistance: hit.resistance,
      flavor_text: hit.flavor_text,
      confidence,
    };
  }

  const category = categoryHint ?? 'Other';
  const fallback = CATEGORY_FALLBACKS[category];
  return {
    common_name: commonName || 'Unidentified Plant',
    scientific_name: scientificName || '',
    ...fallback,
    confidence,
  };
}
